
services:
  db:
    build:
      context: .
    container_name: accr_db
    ports:
      - "${DB_PORT_HOST:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped

  scheduler:
    build: .
    command: ["python", "scheduler_runner.py"]
    working_dir: /app
    depends_on:
      - db
    restart: always
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: ${DB_PORT:-5432}

    volumes:
      - ./output:/app/scheduler_output

volumes:
  postgres_data: