version: '3.8'

services:
  db:
    build:
      context: .
    container_name: accr_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: accr_db

volumes:
  postgres_data:
