version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bap_app
    environment:
      - DB_NAME=bap
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "8000:8000"  # Пробрасываем порт, если нужно
    depends_on:
      - db
    restart: always


  db:
    image: postgres:14
    container_name: bap_db
    environment:
      POSTGRES_DB: bap
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
